apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
  namespace: datadog
spec:
  features:
    kubeStateMetricsCore:
      enabled: true
    clusterChecks:
      enabled: true
    logCollection:
      enabled: false
  global:
    clusterName: ksc-issue-reproduction
    credentials:
      apiSecret:
        keyName: api-key
        secretName: datadog-secrets
    site: datadoghq.com
    kubelet:
      tlsVerify: false
